import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import {
  Hero,
  WhoWeAre,
  FinancialHighlights,
  ViewsFromOurLeaders,
  OurPerformance,
  TheWayWeCreateValue,
  SustainabilityPerformance,
  Leadership,
  Downloads,
} from "@/sections";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UMW Holdings Integrated Annual Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Hero />
      <WhoWeAre />
      <FinancialHighlights />
      <ViewsFromOurLeaders />
      <OurPerformance />
      <TheWayWeCreateValue />
      <SustainabilityPerformance />
      <Leadership />
      <Downloads />
    </>
  );
}
