import Head from "next/head";
// import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { Navbar1 } from "@/components";
import Image from "next/image";
import images from "@/constants/images";

import {
  Hero,
  WhoWeAre,
  FinancialHighlights,
  ViewsFromOurLeaders,
  OurPerformance,
  TheWayWeCreateValue,
  SustainabilityPerformance,
  Leadership,
  AGM,
  Downloads,
} from "@/sections";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UMW Holdings Integrated Annual Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      {/* <p className={styles.watermark}>INTEGRATED ANNUAL REPORT 2022</p> */}
      <Navbar1 className={styles.navbar} />

      <Hero />

      <WhoWeAre />

      <FinancialHighlights />

      <ViewsFromOurLeaders />

      <OurPerformance />

      <TheWayWeCreateValue />

      <SustainabilityPerformance />

      <Leadership />

      <AGM />

      <Downloads />

      <div className={styles.copyright}>
        <p className={styles["text"]}>
          © 2023 UMW Holdings Berhad 198201010554 (90278-P). All rights
          reserved.
        </p>
      </div>
    </>
  );
}
